exclude = [".git", ".venv", ".vscode", ".devcontainer", "docker"]
line-length = 79
indent-width = 4

[lint]
extend-select = ["E501"]


[format]
<<<<<<< HEAD
quotes-style = "double"
=======
quote-style = "double"
>>>>>>> c04e987 (init commit)
indent-style = "space"